// WebTest.idl : IDL source for WebTest
//

// This file will be processed by the MIDL tool to
// produce the type library (WebTest.tlb) and marshalling code.

#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(C5315687-7FBE-4168-AEE3-F48C8B21954A),
	dual,
	nonextensible,
	helpstring("IThreadEvent Interface"),
	pointer_default(unique)
]
interface IThreadEvent : IDispatch{
	[id(1), helpstring("method Start")] HRESULT Start(void);
	[id(2), helpstring("method Stop")] HRESULT Stop(void);
	[id(3), helpstring("method SetPos")] HRESULT SetPos([in] ULONG nPos);
};

[
	object,
	uuid(FBDC0BC5-2B90-4A27-A520-0C3E0654BDF8),
	dual,
	nonextensible,
	helpstring("ICallBack Interface"),
	pointer_default(unique)
]
interface ICallBack : IDispatch{
	[propget, id(1), helpstring("property CallBack")] HRESULT CallBack([out, retval] VARIANT* pVal);
	[propput, id(1), helpstring("property CallBack")] HRESULT CallBack([in] VARIANT newVal);
	[id(2), helpstring("method DoWork")] HRESULT DoWork(void);
	[id(3), helpstring("method SetCallBack")] HRESULT SetCallBack([in] VARIANT var);
};
[
	object,
	uuid(62F069C8-CA28-4F7F-8017-CF5DF453E922),
	dual,
	nonextensible,
	helpstring("IMiniObject Interface"),
	pointer_default(unique)
]
interface IMiniObject : IDispatch{
	[propput, id(1), helpstring("property CallBack")] HRESULT CallBack([in] IDispatch* newVal);
	[id(2), helpstring("method Do")] HRESULT Do(void);
};

[
	uuid(F42060E2-B894-477F-8A1F-96FDD088051A),
	version(1.0),
	helpstring("WebTest 1.0 Type Library")
]
library WebTestLib
{
	importlib("stdole2.tlb");
	[
		uuid(D99756EA-6CDD-438D-AD50-E90608FDBDAB),
		helpstring("_IThreadEventEvents interface")
	]
	dispinterface _IThreadEventEvents
	{
		properties:
		methods:
		[id(1), helpstring("method OnProgress")] HRESULT OnProgress([in] ULONG nPos);
	}
	[
		uuid(FCD3826B-72C0-423A-B792-37EF54B3B62D),
		helpstring("ThreadEvent Class")
	]
	coclass ThreadEvent
	{
		[default] interface IThreadEvent;
		[default, source] dispinterface _IThreadEventEvents;
	};
	[
		uuid(695E2785-111E-4E6A-9FF4-A3C24FD4D9C7),
		helpstring("CallBack Class")
	]
	coclass CallBack
	{
		[default] interface ICallBack;
	};
	[
		uuid(A7E5B589-3014-46CB-8F97-DA621FA09690),
		helpstring("MiniObject Class")
	]
	coclass MiniObject
	{
		[default] interface IMiniObject;
	};
};
