#pragma once

template <class T>
class CProxy_IWebPluginsEvents : public IConnectionPointImpl<T, &__uuidof(_IWebPluginsEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
