#pragma once

template <class T>
class CProxy_IIEWebPluginEvents : public IConnectionPointImpl<T, &__uuidof(_IIEWebPluginEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
