// XWebPlugins2.idl : IDL source for XWebPlugins2
//

// This file will be processed by the MIDL tool to
// produce the type library (XWebPlugins2.tlb) and marshalling code.

#include "olectl.h"
#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";


[
	object,
	uuid(5077BB90-4C02-44AE-BC08-5AE599A4A1A0),
	dual,
	nonextensible,
	helpstring("IIEWebPlugin Interface"),
	pointer_default(unique)
]
interface IIEWebPlugin : IDispatch{
};

[
	uuid(3E9834D3-0327-46BF-8DEC-2CEC083E958B),
	version(1.0),
	helpstring("XWebPlugins2 1.0 Type Library")
]
library XWebPlugins2Lib
{
	importlib("stdole2.tlb");

	[
		uuid(94C4BE48-5122-4823-960E-823E62393209),
		control,
		helpstring("IEWebPlugin Class")
	]
	coclass IEWebPlugin
	{
		[default] interface IIEWebPlugin;
	};
};
